from opentrons import protocol_api, labware, instruments
import json

metadata = {

    'protocolName': 'twist_remapping',
    'author': 'Hannah Verdonk <hverdonk@stanford.edu>',
    'apiLevel': '2.2'}


def run(protocol_context):
    # labware setup
    tiprack_10ul = protocol_context.load_labware('geb_96_tiprack_10ul', '11')
    deepwell = protocol_context.load_labware("usascientific_96_wellplate_2.4ml_deep", '10')
    plate_inc_10 = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '1')
    plate_24w = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '2')
    plate_20w = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '3')
    plate_19w = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '4')
    plate_23w = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '5')
    plate_inc_11 = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '6')
    plate_22w = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '7')
    plate_21w = protocol_context.load_labware("corning_96_wellplate_360ul_flat", '8')

    # instrument setup
    p10 = protocol_context.load_instrument('p10_single', 'left', tip_racks=[tiprack_10ul])

    # Do the transfers
    p10.transfer(5, plate_inc_10.wells_by_name()["A01"], deepwell.wells_by_name()["E12"])
    p10.transfer(5, plate_24w.wells_by_name()["H5"], deepwell.wells_by_name()["F10"])
    p10.transfer(5, plate_24w.wells_by_name()["C4"], deepwell.wells_by_name()["G10"])
    p10.transfer(5, plate_24w.wells_by_name()["G5"], deepwell.wells_by_name()["H10"])
    p10.transfer(5, plate_24w.wells_by_name()["E3"], deepwell.wells_by_name()["A11"])
    p10.transfer(5, plate_24w.wells_by_name()["H4"], deepwell.wells_by_name()["B11"])
    p10.transfer(5, plate_24w.wells_by_name()["F3"], deepwell.wells_by_name()["C11"])
    p10.transfer(5, plate_24w.wells_by_name()["F2"], deepwell.wells_by_name()["D11"])
    p10.transfer(5, plate_24w.wells_by_name()["F4"], deepwell.wells_by_name()["E11"])
    p10.transfer(5, plate_24w.wells_by_name()["D2"], deepwell.wells_by_name()["F11"])
    p10.transfer(5, plate_24w.wells_by_name()["G4"], deepwell.wells_by_name()["G11"])
    p10.transfer(5, plate_24w.wells_by_name()["C3"], deepwell.wells_by_name()["H11"])
    p10.transfer(5, plate_24w.wells_by_name()["E5"], deepwell.wells_by_name()["A12"])
    p10.transfer(5, plate_24w.wells_by_name()["C6"], deepwell.wells_by_name()["B12"])
    p10.transfer(5, plate_24w.wells_by_name()["D6"], deepwell.wells_by_name()["C12"])
    p10.transfer(5, plate_24w.wells_by_name()["C5"], deepwell.wells_by_name()["D12"])
    p10.transfer(5, plate_20w.wells_by_name()["D2"], deepwell.wells_by_name()["F3"])
    p10.transfer(5, plate_20w.wells_by_name()["H3"], deepwell.wells_by_name()["G3"])
    p10.transfer(5, plate_20w.wells_by_name()["E4"], deepwell.wells_by_name()["H3"])
    p10.transfer(5, plate_20w.wells_by_name()["H7"], deepwell.wells_by_name()["A4"])
    p10.transfer(5, plate_20w.wells_by_name()["C3"], deepwell.wells_by_name()["B4"])
    p10.transfer(5, plate_20w.wells_by_name()["F4"], deepwell.wells_by_name()["C4"])
    p10.transfer(5, plate_20w.wells_by_name()["G3"], deepwell.wells_by_name()["D4"])
    p10.transfer(5, plate_20w.wells_by_name()["A5"], deepwell.wells_by_name()["E4"])
    p10.transfer(5, plate_20w.wells_by_name()["A1"], deepwell.wells_by_name()["F4"])
    p10.transfer(5, plate_20w.wells_by_name()["D1"], deepwell.wells_by_name()["G4"])
    p10.transfer(5, plate_20w.wells_by_name()["H2"], deepwell.wells_by_name()["H4"])
    p10.transfer(5, plate_20w.wells_by_name()["D12"], deepwell.wells_by_name()["A5"])
    p10.transfer(5, plate_20w.wells_by_name()["H12"], deepwell.wells_by_name()["B5"])
    p10.transfer(5, plate_20w.wells_by_name()["C4"], deepwell.wells_by_name()["C5"])
    p10.transfer(5, plate_20w.wells_by_name()["F3"], deepwell.wells_by_name()["D5"])
    p10.transfer(5, plate_20w.wells_by_name()["F2"], deepwell.wells_by_name()["E5"])
    p10.transfer(5, plate_20w.wells_by_name()["A2"], deepwell.wells_by_name()["F5"])
    p10.transfer(5, plate_20w.wells_by_name()["D4"], deepwell.wells_by_name()["G5"])
    p10.transfer(5, plate_20w.wells_by_name()["G2"], deepwell.wells_by_name()["H5"])
    p10.transfer(5, plate_20w.wells_by_name()["D7"], deepwell.wells_by_name()["A6"])
    p10.transfer(5, plate_20w.wells_by_name()["B4"], deepwell.wells_by_name()["B6"])
    p10.transfer(5, plate_20w.wells_by_name()["G11"], deepwell.wells_by_name()["C6"])
    p10.transfer(5, plate_20w.wells_by_name()["E3"], deepwell.wells_by_name()["D6"])
    p10.transfer(5, plate_19w.wells_by_name()["E9"], deepwell.wells_by_name()["A1"])
    p10.transfer(5, plate_19w.wells_by_name()["H8"], deepwell.wells_by_name()["B1"])
    p10.transfer(5, plate_19w.wells_by_name()["B5"], deepwell.wells_by_name()["C1"])
    p10.transfer(5, plate_19w.wells_by_name()["G11"], deepwell.wells_by_name()["D1"])
    p10.transfer(5, plate_19w.wells_by_name()["E1"], deepwell.wells_by_name()["E1"])
    p10.transfer(5, plate_19w.wells_by_name()["E8"], deepwell.wells_by_name()["F1"])
    p10.transfer(5, plate_19w.wells_by_name()["E11"], deepwell.wells_by_name()["G1"])
    p10.transfer(5, plate_19w.wells_by_name()["E12"], deepwell.wells_by_name()["H1"])
    p10.transfer(5, plate_19w.wells_by_name()["D4"], deepwell.wells_by_name()["A2"])
    p10.transfer(5, plate_19w.wells_by_name()["E5"], deepwell.wells_by_name()["B2"])
    p10.transfer(5, plate_19w.wells_by_name()["F3"], deepwell.wells_by_name()["C2"])
    p10.transfer(5, plate_19w.wells_by_name()["H1"], deepwell.wells_by_name()["D2"])
    p10.transfer(5, plate_19w.wells_by_name()["H5"], deepwell.wells_by_name()["E2"])
    p10.transfer(5, plate_19w.wells_by_name()["F4"], deepwell.wells_by_name()["F2"])
    p10.transfer(5, plate_19w.wells_by_name()["H11"], deepwell.wells_by_name()["G2"])
    p10.transfer(5, plate_19w.wells_by_name()["E7"], deepwell.wells_by_name()["H2"])
    p10.transfer(5, plate_19w.wells_by_name()["F2"], deepwell.wells_by_name()["A3"])
    p10.transfer(5, plate_19w.wells_by_name()["H7"], deepwell.wells_by_name()["B3"])
    p10.transfer(5, plate_19w.wells_by_name()["H9"], deepwell.wells_by_name()["C3"])
    p10.transfer(5, plate_19w.wells_by_name()["H12"], deepwell.wells_by_name()["D3"])
    p10.transfer(5, plate_19w.wells_by_name()["E3"], deepwell.wells_by_name()["E3"])
    p10.transfer(5, plate_23w.wells_by_name()["B10"], deepwell.wells_by_name()["C10"])
    p10.transfer(5, plate_23w.wells_by_name()["G9"], deepwell.wells_by_name()["D10"])
    p10.transfer(5, plate_23w.wells_by_name()["F9"], deepwell.wells_by_name()["E10"])
    p10.transfer(5, plate_inc_11.wells_by_name()["H03"], deepwell.wells_by_name()["F12"])
    p10.transfer(5, plate_inc_11.wells_by_name()["B07"], deepwell.wells_by_name()["G12"])
    p10.transfer(5, plate_inc_11.wells_by_name()["A09"], deepwell.wells_by_name()["H12"])
    p10.transfer(5, plate_22w.wells_by_name()["E6"], deepwell.wells_by_name()["H9"])
    p10.transfer(5, plate_22w.wells_by_name()["A5"], deepwell.wells_by_name()["A10"])
    p10.transfer(5, plate_22w.wells_by_name()["D6"], deepwell.wells_by_name()["B10"])
    p10.transfer(5, plate_21w.wells_by_name()["F2"], deepwell.wells_by_name()["E6"])
    p10.transfer(5, plate_21w.wells_by_name()["A2"], deepwell.wells_by_name()["F6"])
    p10.transfer(5, plate_21w.wells_by_name()["G3"], deepwell.wells_by_name()["G6"])
    p10.transfer(5, plate_21w.wells_by_name()["C6"], deepwell.wells_by_name()["H6"])
    p10.transfer(5, plate_21w.wells_by_name()["C4"], deepwell.wells_by_name()["A7"])
    p10.transfer(5, plate_21w.wells_by_name()["F3"], deepwell.wells_by_name()["B7"])
    p10.transfer(5, plate_21w.wells_by_name()["G5"], deepwell.wells_by_name()["C7"])
    p10.transfer(5, plate_21w.wells_by_name()["D4"], deepwell.wells_by_name()["D7"])
    p10.transfer(5, plate_21w.wells_by_name()["E2"], deepwell.wells_by_name()["E7"])
    p10.transfer(5, plate_21w.wells_by_name()["A7"], deepwell.wells_by_name()["F7"])
    p10.transfer(5, plate_21w.wells_by_name()["G1"], deepwell.wells_by_name()["G7"])
    p10.transfer(5, plate_21w.wells_by_name()["F1"], deepwell.wells_by_name()["H7"])
    p10.transfer(5, plate_21w.wells_by_name()["B6"], deepwell.wells_by_name()["A8"])
    p10.transfer(5, plate_21w.wells_by_name()["C2"], deepwell.wells_by_name()["B8"])
    p10.transfer(5, plate_21w.wells_by_name()["H5"], deepwell.wells_by_name()["C8"])
    p10.transfer(5, plate_21w.wells_by_name()["E3"], deepwell.wells_by_name()["D8"])
    p10.transfer(5, plate_21w.wells_by_name()["F4"], deepwell.wells_by_name()["E8"])
    p10.transfer(5, plate_21w.wells_by_name()["D3"], deepwell.wells_by_name()["F8"])
    p10.transfer(5, plate_21w.wells_by_name()["B5"], deepwell.wells_by_name()["G8"])
    p10.transfer(5, plate_21w.wells_by_name()["H1"], deepwell.wells_by_name()["H8"])
    p10.transfer(5, plate_21w.wells_by_name()["H2"], deepwell.wells_by_name()["A9"])
    p10.transfer(5, plate_21w.wells_by_name()["H3"], deepwell.wells_by_name()["B9"])
    p10.transfer(5, plate_21w.wells_by_name()["A1"], deepwell.wells_by_name()["C9"])
    p10.transfer(5, plate_21w.wells_by_name()["A5"], deepwell.wells_by_name()["D9"])
    p10.transfer(5, plate_21w.wells_by_name()["B3"], deepwell.wells_by_name()["E9"])
    p10.transfer(5, plate_21w.wells_by_name()["A6"], deepwell.wells_by_name()["F9"])
    p10.transfer(5, plate_21w.wells_by_name()["C3"], deepwell.wells_by_name()["G9"])
